version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    golang-x:
      patterns:
      - "golang.org/x/*"
    k8s:
      patterns:
      - "k8s.io/*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: gomod
  directory: /website
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: /website
  schedule:
    interval: daily
